# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(max_length=16)),
                ('faq_type', models.IntegerField(default=999)),
            ],
        ),
    ]
