# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20190429_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='faq_answer',
            field=models.TextField(default='\ub2f5\ubcc0'),
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_question',
            field=models.TextField(default='\uc9c8\ubb38'),
        ),
    ]
