# Generated by Django 2.2 on 2019-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20190429_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_id',
            field=models.TextField(default='0000000000000001'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.TextField(default='999'),
        ),
    ]
