# Generated by Django 2.2 on 2019-05-17 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_auto_20190515_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(default=datetime.datetime(2019, 5, 17, 18, 14, 20, 434495))),
                ('log_userid', models.CharField(max_length=60)),
                ('log_question', models.TextField(default='질문')),
                ('log_answer', models.TextField(default='답변')),
            ],
        ),
    ]
