# Generated by Django 2.2 on 2019-05-17 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
