# Generated by Django 2.2 on 2019-05-20 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_auto_20190517_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
